### ISSUE TITLE
"Unable to load Java Runtime Environment" Error

### ISSUE THREAD

**Issue by Fritzerton** [z-classic/zclassic-full-node-wallet#15]
<img width="422" alt="screen shot 2018-02-16 at 5 51 44 pm" src="https://user-images.githubusercontent.com/35083649/36332902-21d07608-1342-11e8-91b2-5f9c80da4969.png">

Error pops up when opening wallet. Running High Sierra 10.13.3

**Comment by ch4ot1c** [comment]
https://java.com/en/download/ Does installing this fix it?

**Comment by Fritzerton** [comment]
Yes
