### ISSUE TITLE
Zclassic swing wallet error

### ISSUE THREAD

**Issue by zclassicmeng** [z-classic/zclassic-full-node-wallet#38]
Hi guys, 

I  have the beta wallet. It was working fine yesterday. Today when I open it, it shows me this error message. How do I resolve this. I have coins in my wallet. Please help.

![zclassic error](https://user-images.githubusercontent.com/36235701/35923645-6dcbdbdc-0be6-11e8-8969-cb9959f92597.JPG)

TIA.

**Comment by nimbosa** [comment]
this is a Full Node via GUI wallet (Swing UI), duly transferred

**Comment by nimbosa** [comment]
this is a stale issue and now fixed, default network connections to nodes are back to plenty!
